baseURL = 'https://dudung.github.io/lumpur-note'
languageCode = 'en-us'
title = 'lumpur-note'
theme = 'lunote'

enableEmoji = true

[pagination]
pagerSize = 16

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = 'Home'
  weight = 2
  identifier = 'home'
  url = '/'
